---
title: "네이버 웹툰 크롤링 및 분석"
author: "조민재"
date: '2020년 12월 13일'
output: html_document
---
# 주제 선정 이유


# 크롤링



# 분석

```{r}
#install.packages("ggplot2")
library(ggplot2)
```

```{r}
info_df <- read.csv("info_df.csv") # 웹툰 정보를 담은 데이터프레임 불러옴.
```

## 장르 비율 분석

### 서사 방식(스토리, 에피소드, 옴니버스) 포함
```{r}
all_genre <- table(info_df$genre)
label <- paste(names(all_genre), "\n", all_genre)

pie(all_genre, labels=label, radius=1.3)
```
### 서사 방식(스토리, 에피소드, 옴니버스) 비율
```{r}
split_genre_narrative <-  info_df$genre %>%
  strsplit(split=",")

narrative_method <- c()
for(i in 1:length(split_genre_narrative)){
  narrative_method <- append(narrative_method, split_genre_narrative[[i]][1])
}
narrative_method <- table(narrative_method)

label <- paste(names(narrative_method), "\n", narrative_method)
pie(narrative_method, labels=label, radius=0.8)
```

### 서사 방식(스토리, 에피소드, 옴니버스) 미포함 장르 비율
```{r}
genre <- c()
for(i in 1:length(split_genre_narrative)){
  genre <- append(genre, split_genre_narrative[[i]][2])
}
genre <- table(genre)

label <- paste(names(genre), "\n", genre)
pie(genre, labels=label, radius=1.2)
```



## 인기 많은 웹툰 장르 분석
```{r}

```

## 장르별 웹툰 순위
```{r}

```


